language: cpp
os: linux
dist: bionic

compiler:
  - gcc
  - clang

env:
  global:
    - CXXFLAGS="-Wall -Wextra -Wno-unused-parameter"
  jobs:
    - OROCOS_KDL_BUILD_TYPE=Debug
    - OROCOS_KDL_BUILD_TYPE=Release

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y libeigen3-dev libcppunit-dev python-sip-dev python3-sip-dev python-psutil python3-psutil python-future python3-future
  # build orocos_kdl
  - cd orocos_kdl
  - mkdir build
  - cd build
  - cmake -DENABLE_TESTS:BOOL=ON -DCMAKE_BUILD_TYPE=${OROCOS_KDL_BUILD_TYPE} -DENABLE_MODELS:BOOL=ON -DENABLE_EXAMPLES:BOOL=ON ./..
  # compile and install orocos_kdl
  - make
  - sudo make install
  - cd ../..

script:
  # execute orocos_kdl tests
  - cd orocos_kdl/build
  - make check
  - cd ../..
  # execute examples
  - ./build/examples/trajectory_example
  - ./build/examples/geometry
